#version: '2.1'
#orbs:
#  aws-cli: circleci/aws-cli@5.1
#  aws-ecr: circleci/aws-ecr@9.0
#workflows:
#  build_and_push_image:
#    jobs:
#      - aws-ecr/build_and_push_image:
#          auth:
#            - aws-cli/setup:
#          account_id: ${AWS_ACCOUNT_ID}
#          context: aws-creds 
#          dockerfile: Dockerfile
#          #executors: base
#          push_image: true
#          region: eu-west-1 
#          repo: isa/python-demo 
#          tag: isa
#
version: 2.1

orbs:
  mibaboo: isa-ns/mibaboo@dev:three

workflows:
  build-and-push:
    jobs:
      - mibaboo/build_and_push:
          context: aws-shared  # your context with AWS credentials
          repo: isa/python-demo         # your ECR repository name
          #region: us-east-1    # your AWS region
          #account_id: ${AWS_ACCOUNT_ID}
          tag: ${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          #create_repo: true    # creates ECR repo if it doesn't exist
          #repo_scan_on_push: true  

