# .circleci/config.yml
version: 2.1

# Define reusable executors (environments)
executors:
  docker-build-executor:
    docker:
      - image: cimg/base:2024.06
    resource_class: large
    environment:
      DOCKER_BUILDKIT: 1

# Define jobs
jobs:
  build_and_push_image:
    parameters:
      app_name:
        type: string
        default: "python-demo"
      aws_region:
        type: string
        default: "eu-west-1"
    executor: docker-build-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Get short Git hash
          command: |
            SHORT_HASH=$(git rev-parse --short=7 HEAD)
            echo "export SHORT_HASH=$SHORT_HASH" >> "$BASH_ENV"
            echo "Full git hash: $(git rev-parse HEAD)"
            echo "Short git hash: $SHORT_HASH"

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y curl unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

      - run:
          name: Build Docker image
          command: |
            docker build -t isa/<< parameters.app_name >>:main-$SHORT_HASH .

      - run:
          name: Authenticate with ECR and Push Docker image
          command: |
            ECR_REGISTRY_ID="294185804746"
            ECR_REPOSITORY="isa/<< parameters.app_name >>"
            IMAGE_TAG="main-$SHORT_HASH"

            echo "Authenticating to ECR..."
            aws ecr get-login-password --region << parameters.aws_region >> \
            | docker login \
              --username AWS \
              --password-stdin $ECR_REGISTRY_ID.dkr.ecr.<< parameters.aws_region >>.amazonaws.com

            echo "Pushing Docker image to ECR..."
            docker tag isa/<< parameters.app_name >>:$IMAGE_TAG $ECR_REGISTRY_ID.dkr.ecr.<< parameters.aws_region >>.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY_ID.dkr.ecr.<< parameters.aws_region >>.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

# Define workflows
workflows:
  build_and_push_image_workflow:
    jobs:
      - build_and_push_image:
          context: aws-creds

