apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpdemo
    spec:
      containers:
      - name: phpdemo
        image: mibaboo/docker-phpdemo 
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
