apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpdemo
  name: phpdemo
  namespace: default
spec:
  clusterIP: 10.105.19.110
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-80-80-2vwgf
    nodePort: 31919
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpdemo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

